# File: roles/containers/vault/tasks/main.yml
---
- name: Deploy Vault stack
  tags: [vault]
  vars:
    container_src_path: /home/tallgray1/projects/containers
    container_dest_path: /opt/docker-stacks
  block:
    - name: Ensure Docker Compose is installed
      apt:
        name: docker-compose
        state: present
        update_cache: true

    - name: Ensure destination directory exists
      file:
        path: "{{ container_dest_path }}/vault"
        state: directory
        owner: tallgray1
        group: tallgray1
        mode: '0755'

    - name: Copy Vault docker-compose.yml to target host
      copy:
        src: "{{ container_src_path }}/vault/docker-compose.yml"
        dest: "{{ container_dest_path }}/vault/docker-compose.yml"
        owner: tallgray1
        group: tallgray1
        mode: '0644'

    - name: Copy Vault Dockerfile (optional)
      copy:
        src: "{{ container_src_path }}/vault/Dockerfile"
        dest: "{{ container_dest_path }}/vault/Dockerfile"
        owner: tallgray1
        group: tallgray1
        mode: '0644'
      ignore_errors: true  # Only needed if your Vault stack builds a custom image

    - name: Launch Vault stack
      command: docker-compose up -d
      args:
        chdir: "{{ container_dest_path }}/vault"
