image: python:3.9

before_script:
  - pip install ansible ansible-lint

stages:
  - lint
  - syntax-check

lint:
  stage: lint
  script:
    - ansible-lint playbooks/site.yml

syntax-check:
  stage: syntax-check
  script:
    - ansible-playbook --syntax-check -i inventories/dev/hosts.ini playbooks/site.yml
