---
- hosts: all
  become: true
  tasks:

  - name: Deploy consistent Ubuntu packages
    ansible.builtin.apt:
      update_cache: yes
      name:
        - dnsutils
        - nano
        - python3
      state: latest
    when: ansible_distribution == "Ubuntu"

  # - name: Deploy consistent RHEL/Centos packages
  #   ansible.builtin.apt:
  #     update_cache: yes
  #     name:
  #       dnsutils
  #       nano
  #       python3
  #     state: latest
  #   when: ansible_distribution == "Ubuntu"
