---
- hosts: all
  become: true
  pre_tasks: 

  - name: update repo cache (RedHat)
    tags: always
    yum:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "RedHat"

  - name: update repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  roles:
    - base

- hosts: file_servers
  become: true
  roles:
    - file_servers

- hosts: k8s
  become: true
  roles:
    - k8s

- hosts: master
  become: true
  roles:
    - master

- hosts: workers
  become: true
  roles:
    - workers

- hosts: workstations
  become: true
  roles:
    - workstations
