- name: Add Docker GPG apt Key
  tags: docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  tags: docker
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ distribution_release }} stable
    state: present

- name: Install Docker
  tags: docker
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - docker-compose
    state: latest
    update_cache: true

- name: Install Docker Module for Python
  tags: docker
  pip:
    name: docker

- name: Install Minikube and Helm
  tags: minikube,helm
  package:
    name:
      - minikube
      - helm
    state: latest
