- name: Create type A record
  community.windows.win_dns_record:
    name: "{{ inventory_hostname }}"
    type: "A"
    value: "{{ inventory_ip }}"
    zone: "{{ inventory_zone }}"
  delegate_to: ue1-win006
  # debug: msg="{{ inventory_hostname }}.{{ inventory_zone }}={{ inventory_ip }}"

- name: Create type PTR record
  community.windows.win_dns_record:
    name: "{{ inventory_ip.split('.')[-1] | join() }}"
    type: "PTR"
    value: "{{ inventory_hostname }}.{{ inventory_zone }}"
    zone: "{{ inventory_ip.split('.')[:-1][::-1]|join('.') }}.in-addr.arpa"
  delegate_to: ue1-win006
  # debug: msg="zone={{ inventory_ip.split('.')[:-1][::-1]|join('.') }}.in-addr.arpa, value={{ inventory_hostname }}.{{ inventory_zone }}, name={{ inventory_ip.split('.')[-1] | join() }}"
