- name: Create ansible user
  tags: ansible_user
  user:
    name: ansible
    groups: root

- name: Add ssh key for ansible
  tags: ansible_user
  authorized_key:
    user: ansible
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPN+wxbH4oMKt/lUQ5s+Hrcyw8KMwhZqiZgTph2nD7QX ansible"

- name: Add sudoers file for ansible
  tags: ansible_user
  copy:
    src: sudoer_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440

- name: Install required system packages for (Ubuntu)
  tags: system_packages
  package:
    name:
      - apt-transport-https
      - nano
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - python3-setuptools
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Install required system packages for (CentOS)
  tags: system_packages
  package:
    name:
      - nano
      - ca-certificates
      - curl
      - dnf
      - python3-pip
      - python3-setuptools
    state: latest
  when: ansible_distribution == "CentOS"
