- name: create ansible user
  tags: always
  user:
    name: ansible
    groups: root

- name: add ssh key for ansible
  tags: always
  authorized_key:
    user: ansible
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPN+wxbH4oMKt/lUQ5s+Hrcyw8KMwhZqiZgTph2nD7QX ansible"

- name: add sudoers file for ansible
  tags: always
  copy:
    src: sudoer_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440

- name: install required system packages (Ubuntu)
  tags: nano, apt-transport-https, ca-certificates, curl, software-properties-common, python3, pip
  package:
    name:
      - apt-transport-https
      - nano
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - python3-setuptools
    state: latest
    update_cache: true
  when: ansible_distribution == "Ubuntu"

- name: install required system packages (CentOS)
  tags: nano, ca-certificates, curl, python3, pip
  package:
    name:
      - nano
      - ca-certificates
      - curl
      - dnf
      - python3-pip
      - python3-setuptools
    state: latest
    update_cache: true
  when: ansible_distribution == "CentOS"
