---
- name: Deploy Grafana stack
  hosts: docker
  become: true
  vars:
    role_name: grafana
    container_src_path: /home/tallgray1/projects
    container_dest_path: /opt/docker-stacks
  roles:
    - containers/grafana
